# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Our Journey to Patagonia
email: schlachter.schmidt@gmail.com
description: >
  This is our small blog about our trip from Ireland to Germany, onwards to
  Mexico and Cuba, and finally from Columbia to Patagonia.
baseurl: ""
lang: "en"
# Disqus
discus-identifier: topatagonia-xyz-1

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all

# Styling options
sass:
  sass_dir: assets/_sass
  style: compressed

images: '/assets/images/page'

# Build settings
exclude:
  - build.py